name: lint

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches: [ "main" ]

jobs:
  lint:
    name: lint pull request
    runs-on: ubuntu-latest
    steps:
    - name: Debug workflow trigger
      run: |
        echo "Workflow triggered by: ${{ github.event_name }}"
        echo "PR number: ${{ github.event.pull_request.number }}"
        echo "PR title: ${{ github.event.pull_request.title }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.head_ref }}"
    
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Reformat code style
      run: |
        uv run ruff format .

    - name: Check static error
      run: |
        uv run ruff check --show-fixes --output-format=github
